### ISSUE TITLE
Can I run this on a raspberry pi?

### ISSUE THREAD

**Issue by sudochownrwhoami** [schollz/find3#1]
Can I run this on a raspberry pi?

I did try but I got this error:
```
pi@officepi:~/find3/find3 $ sudo docker build -t find3 .
Sending build context to Docker daemon   14.9MB
Step 1/32 : FROM ubuntu:18.04
 ---> 7295fb90f21f
Step 2/32 : RUN apt-get update
 ---> Running in 351b1a998416
The command '/bin/sh -c apt-get update' returned a non-zero code: 139
```

I'm wondering if this is related to the pi's armv6l architecture or possibly a memory limitation?

Any ideas? Thanks!

**Comment by schollz** [comment]
Hey @sudochownrwhoami . There is someone with this exact same issue. I can't replicate it, but you can follow the progress in the slack channel I just made: https://join.slack.com/t/find3/shared_invite/enQtMzI0MjkwMjc3MDYzLWJiZWEzZjU5NTljM2JlYmE1MDY0NThiYmY2NDYwNGYxNTNmNTJjZjFmNjMwNGMwY2UyNzczNzZhZTIxZWY3ODQ.

Anyone else that needs help, please jump in the slack channel and I'll help you out.

**Comment by victorhooi** [comment]
I saw this issue as well on Raspbian Lite, when I used the default Ubuntu package called `docker.io`.

Issue seems to be Docker not pulling down the correct architecture (armf):

I was able to resolve this:

1. Use `apt-get purge` to remove `docker.io`, and away the `/var/lib/docker` directory
2. Install the official Docker package (`docker-ce`) using the convenience script mentioned in the [Find3 Readme](https://github.com/schollz/find3-cli-scanner/blob/bd95b5636576fccfc7a23ebf44908ad9b498e23d/README.md#find3-cli-scanner):

```
curl -sSL https://get.docker.com | sh
```


@sudochownrwhoami Can you confirm if the above works for you?

**Comment by sudochownrwhoami** [comment]
@victorhooi yes, that worked. Thanks!

**Comment by moritzschramm** [comment]
I got error code 139 as well, running a raspberry pi zero. According to this [SO post](https://stackoverflow.com/questions/31297616/what-is-the-authoritative-list-of-docker-run-exit-codes), 139 = 128 (Fatal error signal) + 11 (SIGSEGV). 
Is this because the pi zero only has 512MB memory? I tried to increase the swap to 1.5GB, but that didn't work as well.
I actually think this is because the ubuntu docker image does not support the arm32v6 architecture. What's the reason for using the ubuntu image instead of an alpine image?

**Comment by schollz** [comment]
@moritzschramm How did you install Docker?

**Comment by moritzschramm** [comment]
@shollz `curl -sSL https://get.docker.com | sh`

**Comment by schollz** [comment]
@moritzschramm , hmm I really don't know. I still can't replicate this error when I try. I've tested with the latest Raspbian on Raspberry Pi model 3 and ZeroW without problems

**Comment by moritzschramm** [comment]
Ok, I just created a Docker file only containing 'FROM ubuntu:17.10 RUN apt-get update' and it returned exit code 139, so I am sure there is an issue with the ubuntu docker image when using the pi zero w. I tried building it with [debian](https://hub.docker.com/_/debian/), which works fine, until it tries to install go (apparently the debian image is armel and not armhf, so it there is no go binary).
@schollz what's your docker and kernel version on the pi zero?

**Comment by schollz** [comment]
@moritzschramm I'll check and get back to you

**Comment by pschmitt** [comment]
For Raspberries check the [images from resin.io](https://docs.resin.io/reference/base-images/resin-base-images/#-a-name-base-images-a-base-images-)

**Comment by moritzschramm** [comment]
@pschmitt is that the only change you made to the Dockerfile? I get an error when installing the some python3 modules

**Comment by schollz** [comment]
@moritzschramm Sorry I was mistaken - for some reason I thought you were talking about the CLI tool.

There is not enough memory on a Raspberry Pi Zero to build these docker images. 

You *can* run the CLI tool natively on the Zero. I'm not sure about the FIND3 server, but I assume so (haven't tried it).

**Comment by moritzschramm** [comment]
@schollz ah okay, that explains it. I will try it next week

**Comment by 40345839668** [comment]
2 GB. Bellek ve 320 gb harddisk yeterli ama Aslında 2 gb. bellek yetmiyor asgari 4 gb. lazım sanırım.
