### ISSUE TITLE
How to track bluetooth wearables?

### ISSUE THREAD

**Issue by stefanheijnen** [schollz/find3#100]
How can we track Bluetooth devices? When I'm at home I don't carry my phone around. But I do have a fitness tracker on my arm.

**Comment by schollz** [comment]
Its generally possible using https://github.com/schollz/find3-cli-scanner.

However, I add that you will likely need to develop your own bluetooth device to track it constantly. Most Bluetooth LE devices now have a limited time they are in Discoverable mode, which is the only mode that allows their signal strength to be measured. Usually this is about 30 seconds. However, its possible to buy your own Bluetooth chip and just have it in DIscoverable mode all the time (I've done this). That being said, I'm not sure you can actually track your fitness tracker.

**Comment by stefanheijnen** [comment]
Oke thanks for the clarification.
