### ISSUE TITLE
Android app turns on screen

### ISSUE THREAD

**Issue by stefanheijnen** [schollz/find3#104]
I've the FIND3 android app installed on 2 phones, both android 7.1.2. Every time FIND3 adds bluetooth and/or wifi points it turns on the screen for a few seconds. That's every 1-2 minutes.

How can I prevent this?

Update: I also installed it on an Android 8.1 phone and there it also turns on the screen.

**Comment by schollz** [comment]
See https://github.com/schollz/find3-android-scanner/issues/5
