### ISSUE TITLE
Question: How to learn while passive tracking 

### ISSUE THREAD

**Issue by kappelloss** [schollz/find3#106]
Hello,
I'm trying to track some bluetooth beacons, so I installed the scanner software on some raspberry pi zero w and let them scan in passiv mode. The tracked mac adresses are sucessfully transported to my find3server, but I cant't locate them because of the missing location learning. Can  I learn with my raspberry's ? And How ?

Thanks in advance,
Dominik

**Comment by austhou** [comment]
did you find a solution to this?
