### ISSUE TITLE
MQTT endpoint for POST /passive

### ISSUE THREAD

**Issue by MatsNl** [schollz/find3#107]
Hi,

First of all, thanks for a great piece of software!

I'm hoping to combine FIND with some very low power BLE scanners, currently submitting their output to mqtt. Would be great if this continuous stream of mqtt data could land in FIND's passive scanner, s.t. I can follow BT only devices (e.g. xiaomi miband3 can be tracked almost live this way). 
I think that requires 2 changes:

- MQTT listener for passive/reverse scanning (current form is active only right?)
- Accept sensordata without wifi fingerprints (if BT or other data is available)

Unless I misunderstood, the current MQTT listener posts data as if they were active scan results correct?
I could make sure MQTT data is submitted conform your sensordata model, or in the current hexrssi format.

What do you think?
Cheers

**Comment by schollz** [comment]
@MatsNl Sounds like a cool project. You can already send data - any kind that you want. If you just want to send Bluetooth you can just do:

```json
{  
   "d":"DEVICE",
   "f":"FAMILY",
   "s":{  
      "bluetooth":{  
         "20:25:64:b7:91:42":-72,
         "20:25:64:b8:06:38":-81,    
      }
   }
}
```

Being able to submit passive fingerprints to MQTT is currently not possible. I can open an endpoint for it. To make things easier, would be okay to use JSON for the endpoint?

Also, I'm curious, what are you using as your BLE scanners that can send MQTT? I'd like to test the setup so itd be great if I can get as close to your setup as I can.

**Comment by MatsNl** [comment]
Cool, JSON would work perfectly! I tried branching myself but I'm far from proficient in Go, and it's not the easiest to debug :)

I'm using this room-assistant plugin, I find the frequent scanning of bluetooth more effective than wifi because in my area there is a lot of noise (I think moving neighbour devices are the main concern). But it still needs triangulation which I hope to do through FIND

https://github.com/mKeRix/room-assistant

**Comment by schollz** [comment]
Ohh, interesting. Actually I thought you needed MQTT because you are using something embedded.

For your scenario though, maybe there is an alternative solution...you could directly use the [find3-cli-scanner](https://github.com/schollz/find3-cli-scanner)* with just Bluetooth in passive mode. You could run it on a computer in the room and it will scan for bluetooth constantly. This is all room-assistant does right? Its not MQTT, but unless you are using 4G I don't think it should make a huge difference.

*currently this is not possible to do with the scanner (the scanner always tries do send WiFi), but I could easily amend it to allow only Bluetooth.

**Comment by schollz** [comment]
@MatsNl, also if you don't mind - what kind of bluetooth devices are you tracking? I've found Bluetooth is generally hard to track because you need them to be in "discoverable" mode to determine the distance and most devices don't allow a prolonged discoverable mode. Even some Bluetooth tags I've found only allow you to determine distance if you pair with them, not in discoverable mode. I've had to make my own that are always "discoverable" but I would love to know if there are some ones already on the market

**Comment by MatsNl** [comment]
I indeed started out with your cli-scanner, but couldn't get it in a bluetooth only mode. If easier, happy to use another solution. Not sure whether pizero W are able to run your scanner? Could give it a shot of course, but given the additional functionality I thought it may be a stretch.

I use miband3 (xiaomi) which can be set in a permanent discoverable mode. Indeed has some battery impact, but it still easily makes ~2 weeks on a charge. RSSI can be tracked without pairing actually, at least the room-assistant tool does. Currently I have 1s scan intervals, which results in quite frequent updating compared to other methods

**Comment by schollz** [comment]
Okay I just pushed some changes so you can run bluetooth by itself. The command will be 

```
find3-cli-scanner -device DEVICE -family FAMILY -bluetooth -forever
```

why don't you try that and see if it works? Make sure to `go get -u github.com/schollz/find3-cli-scanner` to get the latest.

**Comment by schollz** [comment]
There is not enough memory on the Pi Zero to build the docker image for the find3-cli-scanner. Its very easy to install from source though

**Comment by MatsNl** [comment]
Working now, nice! 
Is it possible to reduce the bluetooth scantime? Potentially only listening for specified mac addresses (if necessary to achieve)? Currently the "btmgt find" command isn't responding to --scantime parameter, or am I doing something wrong?

With the JS tool I mentioned earlier, scanning could be increased to multiple times/second. Not necessary for accurate indoor tracking, but the current 90 seconds is quite long. Any ideas?

**Comment by schollz** [comment]
Bluetooth scantime is a big ask. I made a fork that uses a Go library to do
it much faster (~seconds) but I found (and others reported similarly) that
it can cause a power down of the bluetooth adapter that needs a hard reset
to come back online.

An alternative method to capture the output of the btmgmt command and
killing the process also doesn't work because for some reason it's output
isn't finished it finishes the program (even though running the command
seems to indicate otherwise).

What is the tool you refer to that can do bluetooth scans multiple times
per second? Maybe that code can just be adapted for this project.

**Comment by schollz** [comment]
@MatsNl Miraculously I found a bluetooth library that can scan for set times, that doesn't cause disruptions! I just pushed it: https://github.com/schollz/find3-cli-scanner/commit/d7edff42e6bbe15c06a3cdb30fdbb3fc9d4f3ea7

Try it out. You can set the scan time with `-bluetooth -s 3` (3 seconds).

**Comment by MatsNl** [comment]
Awesome, will give it a try when I get home later today! 
I was using room-assistant before, based on node.js. RA doesn't offer the triangulation/ ML though, that was why initially I asked for a mqtt endpoint for passive (to link them both up) :)

**Comment by MatsNl** [comment]
Sorry for the delay, only got around to testing it now. It seems to be working on the first go, completing a scan successfully after ~5 seconds. but then on the second, I get the following:
`
2018-07-25 23:04:02 [ERROR] bluetooth.go scanBluetooth:37 Failed to open device, err: %sno supported devices available `
May be the delay between scans is too short? Command used:
`sudo find3-cli-scanner --device $HOSTNAME --family home --bluetooth -s 5 --forever --server http://192.168.0.3:8003 --passive --debug`

Let me know if you need more info, cheers!

**Comment by schollz** [comment]
​28ed403d3f1f9767b17ed76d402d570dcd89e81b should fix it, try again when you
can!

**Comment by schollz** [comment]
It might not be in your path, try

```
cd $GOPATH/bin
sudo mv find3-cli-scanner /usr/local/bin
```

Paste your other error here.

**Comment by MatsNl** [comment]
Hi!
I actually already had copied the binaries to /usr/local/bin, sho that shouldnt be the problem.. several outstanding issues:

- on RPI3 i can run with sudo only (and therefore not in docker). On RPI the scanning otherwise works perfectly

- on pizero, i cannot get the scanning to work. after first iteration it always fails (even though in bin folder)

```
pi@pizero:/usr/local/bin $ sudo find3-cli-scanner --device $HOSTNAME --family mats --bluetooth -s 5 --forever --server http://192.168.0.3:8003 --passive --debug
2018-07-29 21:31:20 [INFO] main.go func1:185 scanning bluetooth 
2018-07-29 21:31:20 [INFO] main.go func1:191 working in passive mode 
2018-07-29 21:31:20 [DEBUG] bluetooth.go scanBluetooth:31 scanning bluetooth 
2018-07-29 21:31:20 [DEBUG] bluetooth.go onStateChanged:17 gatt powered on 
2018-07-29 21:31:25 [DEBUG] bluetooth.go scanBluetooth:44 bluetooth scan finished 
2018-07-29 21:31:25 [DEBUG] main.go reverseCapture:239 bluetooth data:map[bluetooth:map[REDACTED]] 
2018-07-29 21:31:25 [DEBUG] main.go reverseCapture:249 {
 "t": 1532892680295,
 "f": "AAA",
 "d": "pizero",
 "s": {
  "bluetooth": {
   "11:11:11:11:11:11": -11,
   "11:11:11:11:11:11": -11,
   "11:11:11:11:11:11": -11,
   "11:11:11:11:11:11": -11,
   "11:11:11:11:11:11": -11,
   "11:11:11:11:11:11": -11,
   "11:11:11:11:11:11": -11
  }
 },
 "gps": {}
} 
2018-07-29 21:31:25 [DEBUG] server-main.go postData:47 posting data 
2018-07-29 21:31:25 [DEBUG] server-main.go postData:75 {true inserted 7 fingerprints for mats} 
2018-07-29 21:31:25 [INFO] main.go func1:185 scanning bluetooth 
2018-07-29 21:31:25 [INFO] main.go func1:191 working in passive mode 
2018-07-29 21:31:25 [DEBUG] bluetooth.go scanBluetooth:31 scanning bluetooth 
2018-07-29 21:31:25 [ERROR] bluetooth.go scanBluetooth:37 Failed to open device, err: %sno supported devices available 
pi@pizero:/usr/local/bin $ ls
find3-cli-scanner
pi@pizero:/usr/local/bin $ find
find               find3-cli-scanner  findfs             findmnt            
pi@pizero:/usr/local/bin $ find
find               find3-cli-scanner  findfs             findmnt            
pi@pizero:/usr/local/bin $ find3-cli-scanner --version
find3-cli-scanner version 3.2.2 (92c207 2018-07-25T13:44:00Z)
```

**Comment by MatsNl** [comment]
on pizero w i use the latest downloadable full binary, which returns:
`find3-cli-scanner version 3.2.2 (92c207 2018-07-25T13:44:00Z)`

on rpi3 i use docker build with --no-cache option, can check the version it returns later today

**Comment by schollz** [comment]
Thats why. I thought you were building on source. I uploaded the latest release with bug fixes so you can try that.

**Comment by MatsNl** [comment]
This version works, thanks! Sudo check fails if running under systemctl as root user, but that I can manually work-around :)
