### ISSUE TITLE
Family and location name problems

### ISSUE THREAD

**Issue by heathcliffYang** [schollz/find3#108]
If I name the family 'exp-d,' it will trigger an error: `No learning data available, see the documentation for how to get started with learning.` 

The sever cannot create the corresponding `find3.ai` file even after 300 seconds. The dashboard displays that there are already more than 20 data overall.

**Comment by schollz** [comment]
What happens after you press the calibrate button?
Can you send me your DB?

**Comment by heathcliffYang** [comment]
I have informed you of the DB on your find3 Slack.

**Comment by schollz** [comment]
@heathcliffYang I don't see anything on the Slack, can you paste the link to the message?

**Comment by heathcliffYang** [comment]
This is the link.
https://find3.slack.com/files/UBV4JH6S1/FBV0LRDB4/cszf2cs.sqlite3.db

**Comment by schollz** [comment]
![image](https://user-images.githubusercontent.com/6550035/43139131-d2c354a0-8f05-11e8-899d-02a7a722cf4b.png)

Maybe post it here, since slack doesn't work.

**Comment by heathcliffYang** [comment]
Does this work?
[CSzF2cs.sqlite3.db.zip](https://github.com/schollz/find3/files/2224214/CSzF2cs.sqlite3.db.zip)

Thank you!!

**Comment by schollz** [comment]
@heathcliffYang There is something else going wrong - its not the server, but the client you are using to send the fingerprints. Likely a bug. How did you do the learning?

**Comment by heathcliffYang** [comment]
I followed your instructions, the only difference is family name.
