### ISSUE TITLE
Copyrights & Licensing of MC Escher

### ISSUE THREAD

**Issue by danmarshall** [schollz/find3#113]
Hello,
With all due respect to your excellent project, I feel you should also respect the excellent work of the artist whose work you reference in your image.

> All works by M.C. Escher are copyrighted.
International Copyright laws protect all of the work of M.C. Escher, as well as his spoken and written words. Any reproduction of his work, including downloading, is prohibited without the express written permission of  The M.C. Escher Company, B.V.
Request for Reproduction of Works
If you want to use any of the work of M.C. Escher as illustration in a book, magazine, an advertisement campaign, brochure, or on the Internet, you must submit a request to our Copyright department Attn. Ms. Margareth Verbakel.

https://www.mcescher.com/licensing/

Cheers,
Dan

**Comment by schollz** [comment]
Thanks, request submitted

**Comment by schollz** [comment]
```

**Comment by schollz** [comment]
```
Dear Mr. Scholl,

 

Thank you for your email of the 11th of August.

 

Unfortunately, we are not able to grant our permission for usage of a modified work by M.C. Escher.

Reason is that no work by M.C. Escher may be altered, changed or manipulated in any way.

We trust that you will understand our point of view.

 

Sincerely,

 

Margareth Verbakel

Manager Copyrights
```

I've removed it.
