### ISSUE TITLE
What is the project accuracy?

### ISSUE THREAD

**Issue by hdyztmdqd** [schollz/find3#114]
Hello schollz, would you mind to tell me how accurate your indoor location can be? My indoor project uses knn and naive bayes algorithm too, the acuracy is about 2 meters. I forked your project and checked your csv test data file, it seems your position unit is for large space, such as an office, or a room. But I collect  training data by blocks (1 to 2 meters), so I would like to know what your accuracy is, that will be helpful to me.Thanks.

**Comment by schollz** [comment]
https://www.internalpositioning.com/doc/faq.md#minimum
