### ISSUE TITLE
Images for /view/analysis/<family> do not exist

### ISSUE THREAD

**Issue by eifinger** [schollz/find3#115]
Hi, just upgraded to the newest version (docker) and the images on the view "/view/location_analysis/" return HTTP 400. 
I checked the logs and didn't see any error message but found out that it is loading the images from e.g. "/data/data/images/HxpbrohxLHF/upper_balcony.png".
There is no folder "images"

**Comment by schollz** [comment]
Try going to the Dashboard and clicking "Calibrate machine learning", that should populate it

**Comment by eifinger** [comment]
Works perfectly.
As always thank you for the fast help!
