### ISSUE TITLE
Do bluetooth and wifi measurements get recognized seperately?

### ISSUE THREAD

**Issue by suiluj** [schollz/find3#123]
Hello,
i am planning to add bluetooth or wifi measurements seperately via the API
Some devices support wifi and bluetooth others only bluetooth (e.g. ios)

Is it bad for the AI model when there are fingerprints of the same location, some with wifi and bluetooth, some only bluetooth (in learning mode)?

So when i track devices (some with wifi and bluetooth, some only bluetooth) do the sources get analyzed seperately? Or is there a bad guessing rate because in case of only bluetooth tracking it is missing the wifi signals?

Thanks in advance
suiluj

**Comment by schollz** [comment]
I think it should still work

**Comment by suiluj** [comment]
okay thanks. then i will just try it out.

**Comment by riteshkumarumassedu** [comment]
HI,
Does this system differentiate between WIFI and beacons data? If both beacons data and wifi data is there and does it predict locations based on beacon and wifi separately and then take the average?

**Comment by riteshkumarumassedu** [comment]
HI,
