### ISSUE TITLE
Get method not working.

### ISSUE THREAD

**Issue by rc0302** [schollz/find3#126]
I have followed all the instructions to install and configure find3 on my server. For testing I've used Post /data and it is working but when I use Get  http://xx.xx.xxx.xx:8005/calibrate/family_name im getting error connecting to the address(error:Could not get any response).I tried with postman. Have i missed any points?

**Comment by schollz** [comment]
@rc0302 You are one of several accounts that creates a Github account specifically to post issues to FIND3  (https://github.com/schollz/find3/issues/66#issuecomment-382998197, https://github.com/schollz/find3-cli-scanner/issues/24#issuecomment-428954299, https://github.com/schollz/find3-cli-scanner/issues/18#issuecomment-407441517, https://github.com/schollz/find3/issues/93#issuecomment-392555526). I have some evidence that these accounts come from people who work at a company that want to extract free work from me.

If you work at a company, I do offer consulting and I'm happy to help you for a negotiated (and reasonable) fee. I don't help companies for free. If you are pursuing FIND for fun, then I will need some indication of that from you.

**Comment by schollz** [comment]
Ok, no response in 3 days, closing.
