### ISSUE TITLE
RPI 3: Requires additional package because of missing libf77blas.so.3

### ISSUE THREAD

**Issue by suiluj** [schollz/find3#128]
I had to install this package on a raspberry pi (installed find3 the hard way, not with docker):
```
sudo apt-get install libatlas-base-dev
```

Without this package i got the following error when adding data via the API /data:
```
libf77blas.so.3: cannot open shared object file: No such file or directory
```

I don't know if this is needed in generell.

@schollz Perhaps you could add this hint to the install instructions in case someone gets the same error.

**Comment by Mazotis** [comment]
Fixed with #142
