### ISSUE TITLE
Help with Docker command

### ISSUE THREAD

**Issue by JaviRuiz314** [schollz/find3#137]
Hi, maybe this is not the right place to ask, but I'm building my own server on a Linux virtual machine for a project. I follow the steps on the documentation but on the last one I enter this command 

`$ docker run -p 1884:1883 -p 8005:8003 \`
`-v /home/john/FIND_DATA:/data \`
`-e MQTT_ADMIN=ROOT \`
`-e MQTT_PASS=ROOT \`
`-e MQTT_SERVER='localhost:1883' \`
`-e MQTT_EXTERNAL='192.168.1.15' \`
`-e MQTT_PORT=1884 \`
`--name find3server -d -t schollz/find3`

I found that I always get a "docker invalid reference format" and I'm not sure what's wrong. Any ideas or should I ask on a Docker forum?

**Comment by schollz** [comment]
Try this instead:

```
docker run -p 1884:1883 -p 8005:8003 \
-v /home/john/FIND_DATA:/data \
-e MQTT_ADMIN=ROOT \
-e MQTT_PASS=ROOT \
-e MQTT_SERVER='localhost:1883' \
-e MQTT_EXTERNAL='192.168.1.15' \
-e MQTT_PORT=1884 \
-d -t schollz/find3
```

And if it doesn't work, post the whole output.

**Comment by JaviRuiz314** [comment]
Thank you! That made wonders
