### ISSUE TITLE
502 BAD Gateway

### ISSUE THREAD

**Issue by iudeen** [schollz/find3#148]
It seems like server is down. `502 Bad Gateway`

Is it possible for me to setup my own server to avoid this issue?

**Comment by schollz** [comment]
Server is up now.

I recommend running your own: https://www.internalpositioning.com/doc/server_setup.md

**Comment by iudeen** [comment]
Thank you @schollz 
Yes, I will be creating my own server soon using Raspberry Pi. If I get everything working, I would be happy to donate some amount towards this wonderful initiative.
