### ISSUE TITLE
Track a RaspberryPI

### ISSUE THREAD

**Issue by msanzn** [schollz/find3#151]
I managed to install this project and use my computer as server, (Ubuntu 16.04) and I am able to use the testing from a raspberry Pi to send the example 
`jsons with python3 submit_jsons.py http://IP:PORT testdb.learn.1439597065993.jsons`
 which works.

When I try to use the Raspberry PI as the computer to be tracked I follow the instructions for the command-line scanner (https://www.internalpositioning.com/doc/cli-scanner.md), installing it with docker gives me problems as some files does not download so they are ignored or old ones are used when trying to install docker. And installing natively using the command 

`nohup find3-cli-scanner -i wlan0 -device YOURDEVICE -family YOURFAMILY  -server https://cloud.internalpositioning.com -scantime 10 -bluetooth -forever`

That command gives two errors:

nohup: ignoring input and appending to output nohup.out
nohup: failed to run command find3-cli-scanner command: Permision denied

**Comment by schollz** [comment]
Hi @msanzn. Use `chmod` to add executable permissions.

If you are unsure about how to do that, I suggest searching Stackoverflow or similar.

**Comment by msanzn** [comment]
I have used chmod in the folder that needs to be moved, using it recursively to do it in all the files of the folder. The command was:
'chmod -R 777 /usr/local/bin/find3-cli-scanner'

**Comment by schollz** [comment]
You also need to run the command with sudo
