### ISSUE TITLE
Database or disk is full 

### ISSUE THREAD

**Issue by luis815** [schollz/find3#155]
I've been using this repo for my school project.  So first, @schollz thank you.

I was working on it today, but using the server in the docs (https://cloud.internalpositioning.com/) reports database or disk is full.  

This happens the first time I send training data to the server.  Any data after that times out.  I also briefly saw the same message on the website.

I haven't searched throughly on documentation, but I believe this is a public server for the repo?  If so, how is it maintained?  Or do I have the wrong idea about the issue?

Thanks

**Comment by schollz** [comment]
Should be up now
