### ISSUE TITLE
Images are not found in documentation

### ISSUE THREAD

**Issue by Cerberooo** [schollz/find3#165]
https://www.internalpositioning.com/doc/tracking_your_phone.md

![grafik](https://user-images.githubusercontent.com/16780924/60260413-d62b5500-98d9-11e9-852e-b37218bb0776.png)

**Comment by dmwyatt** [comment]
I was just about to raise this issue myself.

Here's another example:

![image](https://user-images.githubusercontent.com/163359/60772194-96722380-a0b8-11e9-8901-5cb4b90d85bb.png)

Note all the 404s:

![image](https://user-images.githubusercontent.com/163359/60772211-c1f50e00-a0b8-11e9-8cb7-f86f04adf911.png)

**Comment by schollz** [comment]
Thanks, its up now!
