### ISSUE TITLE
Restarting FIND3 server in Docker

### ISSUE THREAD

**Issue by byungwok** [schollz/find3#166]
I wanna know How to restart FIND3 server in Docker for applying the Go file edited.
After touching Go files, and I'd like to apply Go file modified in Find3server docker.
For do this, i'd be restarting Find3 server, but I don't know how to restart this server because it's my first time to deal with  Golang(?).
'docker restart ' on outside from container shell is not the answer.
then  'startup.sh' at the /app dir is not killing the previous server pid himself.
Finally 'go run main.go' is not working with error.

So please let me know how to restart FIND3 server and renew the Go file edited  on docker. 
Thanks

**Comment by schollz** [comment]
If you want to edit the source, build from the source, not using Docker.
