### ISSUE TITLE
Cython module not found building on arm64

### ISSUE THREAD

**Issue by SammyIAm** [schollz/find3#180]
While trying to build the docker image on an arm64 system, numpy and scipy both failed because they were unable to find the 'Cython' module.  I'm not sure if this is a peculiarity of arm64 builds or if it would apply to other architectures, but in order to get it to build I had to add cython to the Dockerfile ([see my changes here](https://github.com/SammyIAm/find3/commit/b81e81a240d38f25aaa24b376e9c5c11ddd147cd)).

Not even sure if I went about fixing that appropriately since I'm still relatively new to Docker, but in case it's helpful for others building the image I figured I'd open an issue.

**Comment by schollz** [comment]
That is weird, as it doesn't use cython...

**Comment by SammyIAm** [comment]
ScyPy's site on [building from source](https://docs.scipy.org/doc/numpy/user/building.html) says:

> To build development versions of NumPy, you’ll need a recent version of Cython. Released NumPy sources on PyPi include the C files generated from Cython code, so for released versions having Cython installed isn’t needed.

And [scipy's setup.py](https://github.com/scipy/scipy/blob/master/setup.py#L274-L294) similarly seems to require it.

It looks like it's only needed under certain building conditions, but running `docker build -t schollz/find3 .` on an arm64 system appears to meet those conditions.

**Comment by donkawechico** [comment]
Seeing the same issue on armhf architecture.

Not a docker guru, but would it be as simple as changing Dockerfile to install Cython before installing scipy/numpy? Something like this?

```
# First set of installations
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget git libc6-dev make pkg-config g++ gcc mosquitto-clients mosquitto python3 python3-dev python3-pip python3-setuptools python3-wheel supervisor libfreetype6-dev python3-matplotlib libopenblas-dev libblas-dev liblapack-dev 

# Install Cython now that we have pip
RUN pip install Cython

# Install scipy
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y python3-scipy python3-numpy
```

**Comment by SammyIAm** [comment]
That's exactly what I did (though I see that my addition of cython to apt-get install is not needed I guess).  Thanks for making this a PR :)

**Comment by donkawechico** [comment]
> That's exactly what I did (though I see that my addition of cython to apt-get install is not needed I guess). 

Did your solution *just* do `apt-get install cython`? Or did you also do a pip install?

Wondering because maybe it'd be simpler to just add cython to the apt-get list rather than this sorta-awkward insertion of a pip command.

**Comment by SammyIAm** [comment]
I linked my code changes up at the top of this issue so you can see
exactly, but I did both because I wasn't sure which was required, and
didn't take the time to reset and try each indiviually.

**Comment by donkawechico** [comment]
Oh, jeez. I read the whole thread but somehow missed the link to your successful changes. Coulda saved myself some effort!
