### ISSUE TITLE
Wrong Location on Map

### ISSUE THREAD

**Issue by OrjwanZaafarani** [schollz/find3#186]
I established the connection between my Raspberry Pi 3 B+ and the server. But, the location of the pi on the map seems to be wrong. What's the problem?

**Comment by nash-stokes** [comment]
At least from my experience, the map serves as a personal reference tool for you to track devices across multiple locations. It does not set the location for you or work off of the data the tracked devices transmit. You have to drag each location pin to where the devices are. I had to also zoom my map view way WAY out before realizing the default location was somewhere off the coast of Africa.

**Comment by OrjwanZaafarani** [comment]
Thank you for your quick response! But, how do I drag each location pin?
<img width="803" alt="Screen Shot 2020-04-02 at 7 52 59 PM" src="https://user-images.githubusercontent.com/61848961/78276420-b0dc0f00-751b-11ea-97d9-2aef8a8a32e2.png">

**Comment by OrjwanZaafarani** [comment]
Thank you!
