### ISSUE TITLE
Completely unstable...

### ISSUE THREAD

**Issue by StefanoGiu** [schollz/find3#194]
Completely unstable... The more I learn data for one room, the more other rooms accuracy drops down. When I start then in tracking mode, the room guessing is not accurate and the scan interval is very high (last seen is more than 5 minutes). As it is, it's completely useless...

**Comment by schollz** [comment]
Why?

**Comment by StefanoGiu** [comment]
Details are above in the text

**Comment by schollz** [comment]
@StefanoGiu Please add more info

**Comment by nash-stokes** [comment]
@StefanoGiu I had better accuracy when I had equal numbers of data points for each room. I'm not sure about your scanning time issue though, as you should be setting this yourself from the command line. 

@schollz One issue I am having is that at a certain point, getting more data does not improve a room's accuracy at all, and in some cases even decreases it. Do you have any suggestions on the amount of data to collect for each room?

**Comment by schollz** [comment]
@nash-stokes Can you make a new issue with your question? Judging by [the Github history of @StefanoGiu](https://github.com/StefanoGiu?tab=overview&from=2020-04-01&to=2020-04-30) they only create issues in projects. I suspect the issue is not with the projects.

**Comment by StefanoGiu** [comment]
Why you closed this? Do you feel I'm trying to denigrate your project?? I was really happy when I was reading the way your project is supposed to work, but unfortunately, I had a very bad experience in tuning the learning up... If you want to collect my feedback, I'm more than welcome to help you understanding the issues I'm facing... otherwise, feel free to ignore it ;)
