### ISSUE TITLE
README.md in Docs refers to www.find3.com - change to https://find3.internalpositioning.com/

### ISSUE THREAD

**Issue by victorhooi** [schollz/find3#2]
The README.md file here:

https://github.com/schollz/find3/blob/d7fa365637509bf31f34167bc08cfc203d687663/docs/README.md

refers to the "www.find3.com" domain. However, this appears to be a squatted domain:

<img width="1167" alt="screen shot 2018-03-04 at 17 25 41" src="https://user-images.githubusercontent.com/243499/36942844-23763ee8-1fd1-11e8-9bf2-afc45dd8b8c6.png">

I believe the URL should be https://find3.internalpositioning.com/

**Comment by schollz** [comment]
Fixed!
