### ISSUE TITLE
Add num_scanners to frontend location page for devices/families

### ISSUE THREAD

**Issue by victorhooi** [schollz/find3#21]
The `by_location` endpoint has a `num_scanners` field which tells us how many Find3 scanners saw this device.

The React frontend page (e.g. http://localhost:8005/view/location/family_name/wifi-02:9f:c2:7d:66:08) should also expose this field as well.

**Comment by schollz** [comment]
7f2aa772fe61862dbda5d892007d20c1cf0e7d4c shows the raw sensor data, which also has this information about number of scanners
