### ISSUE TITLE
Suggestion / Improvement

### ISSUE THREAD

**Issue by hrieke** [schollz/find3#216]
Hi,

It's wonderful project, but I can't help to notice that the files in static (https://github.com/schollz/find3/tree/master/server/main/static) all lack attribution / versions / licenses.
Could you please add this information to the project?

Thank you

**Comment by schollz** [comment]
> all lack attribution / versions / licenses

It [is not true ](https://github.com/schollz/find3/blob/master/server/main/static/css/bootstrap.css#L1-L6) that *all* lack attributes/versions. I may have missed a few though, please let me know which ones are missing. Will accept a PR to fix them.

**Comment by hrieke** [comment]
You know your code better than I, but here's a template:

# Find3 Proudly uses the following open source packages

## Bootstrap, version v4.0.0-beta.3
https://github.com/twbs/bootstrap/
MIT License

## toastr, version 2.1.3
https://github.com/CodeSeven/toastr
MIT License

## normalize.css, 3.0.3
https://github.com/necolas/normalize.css
MIT License

## animate.css, 3.5.2
https://github.com/animate-css/animate.css
http://daneden.me/animate
MIT License

## Font-Awesome, 4.7.0
https://github.com/FortAwesome/Font-Awesome
Code licensed under the MIT License
Fonts licensed under the SIL Open Font License 1.1
SVG Files licensed under the Creative Commons Attribution License 4.0
