### ISSUE TITLE
Shrink Find3 Docker image - Alpine Linux as base?

### ISSUE THREAD

**Issue by victorhooi** [schollz/find3#3]
The Find3 server Docker image is quite large (around 1 GB).

I believe there is room to shrink this.

Advantages:
* Shorter build/rebuild times
* Less packages to download/configure each time
* More secure (smaller security footprint).

[Alpine Linux](https://alpinelinux.org/) is the default base image used by Docker - and might be worth looking into.

(One of the reasons it's on Ubuntu 18.04 is for the latest Bluez - so we'll need to make sure this is still working. However, I believe this is only for the scanning machines.)

I noticed some of the packages may or may not be needed?

Below is from the current [`Dockerfile`](https://github.com/schollz/find3/blob/d7fa365637509bf31f34167bc08cfc203d687663/Dockerfile)
```
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git wget curl vim g++ sqlite3 mosquitto-clients mosquitto python3 python3-dev python3-pip python3-scipy python3-flask python3-sklearn python3-numpy golang supervisor
```

* There's both `curl` and `wget`?
* `vim` may not be required inside the Docker image
* Anything else we can remove?

Current [`ai/requirements.txt`](https://github.com/schollz/find3/blob/d7fa365637509bf31f34167bc08cfc203d687663/server/ai/requirements.txt):
- ujson
- pytest
- pytest-benchmark
- pytest-cov
- sklearn
- numpy
- scipy
- flask
- base58
- tqdm
- expiringdict

**Comment by schollz** [comment]
This is a good idea.

I'm not familiar with Alpine, so I would rather someone try to accommodate that.

**Comment by schollz** [comment]
I merged the Dockerfile into one basic run layer so now its < 400MB.
