### ISSUE TITLE
MQTT api endpoints responding 404 page not found

### ISSUE THREAD

**Issue by alexleekt** [schollz/find3#31]
For the public server. `$ curl https://cloud.internalpositioning.com/api/v1/mqtt/FAMILY`

Expected: 
```
{"message":"Added 'FAMILY' for mqtt. Your passphrase is 'XX'","success":true}
```
Actual:
```
404 page not found% 
```

(This is not an issue for the docker containers.)

**Comment by schollz** [comment]
Sorry, I forgot to implement on the public server, should work now!

https://cloud.internalpositioning.com/api/v1/mqtt/testdb
