### ISSUE TITLE
Add embedded ESP8266 / ESP32 client

### ISSUE THREAD

**Issue by DatanoiseTV** [schollz/find3#37]
I have created a very experimental, early stage client for the ESP32 / ESP8266 microcontroller, which is available from $1. This should allow people to create very cheap beacons.

```
#include <WiFiClientSecure.h>
#include <WiFi.h>
#include <WiFiMulti.h>

WiFiMulti wifiMulti;

const char* ssid     = "SSID";
const char* password = "PASS";

const char* host = "cloud.internalpositioning.com";
const char* ntpServer = "pool.ntp.org";

uint64_t chipid;  

void setup() {
  Serial.begin(115200);
  delay(10);

  // We start by connecting to a WiFi network

  wifiMulti.addAP(ssid, password);

  Serial.println("Connecting Wifi...");
  if (wifiMulti.run() == WL_CONNECTED) {
    Serial.println("");
    Serial.println("WiFi connected");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
    configTime(0, 0, ntpServer);
  }

  

}

unsigned long getTime() {
time_t now;
struct tm timeinfo;
if (!getLocalTime(&timeinfo)) {
Serial.println("Failed to obtain time");
return(0);
}
time(&now);
return now;
}

void SubmitWiFi(void)
{
  String request;
  uint64_t chipid;  

  chipid=ESP.getEfuseMac();//The chip ID is essentially its MAC address(length: 6 bytes).

  String chipIdStr = String((uint32_t)(chipid>>16));

  request += "{\"username\": \"" + chipIdStr + "\", \"group\": \"jooo\", \"wifi-fingerprint\": [";

  int n = WiFi.scanNetworks();
  Serial.println("scan done");
  if (n == 0) {
    Serial.println("no networks found");
  } else {
    Serial.print(n);
    Serial.println(" networks found");
    for (int i = 0; i < n-1; ++i) {


      request += "{\"rssi\": ";
      request += WiFi.RSSI(i);
      request += ", \"mac\": \"";
      request += WiFi.BSSIDstr(i);
      request += "\"}";

      if( (i<n-2) )
      {
        request += ",";
      }


    }

    String localTimeStr = String(getTime());

    request += "], \"location\": \"living room\", \"timestamp\": " + localTimeStr + "000, \"password\": \"frusciante_0128\"}";

    WiFiClientSecure client;
    const int httpsPort = 443;
    if (!client.connect(host, httpsPort)) {
      Serial.println("connection failed");
    }

    // We now create a URI for the request
    String url = "/learn";

    Serial.print("Requesting URL: ");
    Serial.println(url);

    // This will send the request to the server
    client.print(String("POST ") + url + " HTTP/1.1\r\n" +
                 "Host: " + host + "\r\n" +
                 "Content-Type: application/json\r\n" +
                 "Content-Length: " + request.length() + "\r\n\r\n" +
                 request +
                 "\r\n\n\r\n"
                );

    unsigned long timeout = millis();
    while (client.available() == 0) {
      if (millis() - timeout > 5000) {
        Serial.println(">>> Client Timeout !");
        client.stop();
        return;
      }
    }

    // Read all the lines of the reply from server and print them to Serial
    while (client.available()) {
      String line = client.readStringUntil('\r');
      Serial.print(line);
    }

    Serial.println();
    Serial.println("closing connection");

  }
}

void loop() {
  // Use WiFiClient class to create TCP connections
  SubmitWiFi();

  delay(1000);

}
```

Please note this is a very early stage and experimental thing. Any input welcome!

**Comment by schollz** [comment]
Very cool! Maybe you can make a repo for this and I can link to it? That way people could fork / PR.

**Comment by DatanoiseTV** [comment]
@schollz There you go - https://github.com/DatanoiseTV/esp-find3-client

**Comment by schollz** [comment]
Thanks! Updated in the docs. I'm excited to try out your code!

**Comment by DatanoiseTV** [comment]
Thanks @schollz. I have cleaned up the code a lot and now it works perfectly. It syncs time via NTP and uses ArduinoJson to properly serialise the data. Can you please point me how to submit bluetooth scan results in /track and /learn then I will add BLE scanning to ESP32.

**Comment by schollz** [comment]
Cool! I was just thinking about doing that too. Here's the API reference: https://www.internalpositioning.com/doc/api.md#sensor. You can ignore GPS and you can ignore location if you are just doing tracking. Your data will basically just need to look like:

```json
{  
   "d":"DEVICE",
   "f":"FAMILY",
   "t":1520424248897,
   "s":{  
      "bluetooth":{  
         "20:25:64:b7:91:42":-72,
         "20:25:64:b8:06:38":-81,    
      },
      "wifi":{  
         "20:25:64:b7:91:40":-73,
         "70:4d:7b:11:3a:c8":-81,
         "88:d7:f6:a7:2a:4c":-39,
         "8c:0f:6f:e7:2b:78":-42,
         "8c:0f:6f:e7:2b:80":-43,
         "92:0f:6f:e7:2b:80":-43,
         "96:0f:6f:e7:2b:78":-39,
         "9e:0f:6f:e7:2b:80":-43,
         "ac:9e:17:7f:38:a4":-55,
         "dc:fe:07:79:aa:c0":-90,
         "dc:fe:07:79:aa:c3":-89
      }
   }
}
```

Submit this via `POST` to `/data`. If you want to do learning, you use the exact same JSON but also add `"l":"LOCATION"` to specify the location.

**Comment by DatanoiseTV** [comment]
@schollz Is there any possibility to submit BLE results to /learn and /track as well? ArduinoJson seems to have trouble with nested arrays :(

**Comment by DatanoiseTV** [comment]
@schollz BLE support and other goodies added!

**Comment by schollz** [comment]
@DatanoiseTV cool! Did you get over the problem with nested arrays?

**Comment by DatanoiseTV** [comment]
@schollz Yes. All sorted out and BLE added. Using the /data POST endpoint now!

**Comment by schollz** [comment]
@DatanoiseTV Awesome, nice job! I can't wait to try it.

**Comment by DatanoiseTV** [comment]
@schollz I am able to now capture management frames / implement monitor mode on ESP32 for passive scanning. Do I just need the BSSIDs for passive scanning or also the RSSI? What is the request for /passive? Can't see it in the docs.

**Comment by schollz** [comment]
@DatanoiseTV Wow!! I didn't know you could do that with an ESP32! That's so cool. You need both the BSSIDs and the RSSI for passive scanning. Although, if you can't get RSSI maybe we could still use it. For passive data you just do `POST /passive` with similar JSON as before:

```json
{  
   "d":"DEVICE",
   "f":"FAMILY",
   "t":1520424248897,
   "s":{  
      "bluetooth":{  
         "20:25:64:b7:91:42":-72,
         "20:25:64:b8:06:38":-81,    
      },
      "wifi":{  
         "20:25:64:b7:91:40":-73,
         "70:4d:7b:11:3a:c8":-81,
         "88:d7:f6:a7:2a:4c":-39,
         "8c:0f:6f:e7:2b:78":-42,
         "8c:0f:6f:e7:2b:80":-43,
         "92:0f:6f:e7:2b:80":-43,
         "96:0f:6f:e7:2b:78":-39,
         "9e:0f:6f:e7:2b:80":-43,
         "ac:9e:17:7f:38:a4":-55,
         "dc:fe:07:79:aa:c0":-90,
         "dc:fe:07:79:aa:c3":-89
      }
   }
}
```

When this data enters the server, it will automatically collect these and then "reverse" them (so that the DEVICE is actually the sensor and the sensors are actually the devices).

Note also, the bluetooth data is just scanned as before because bluetooth data is device specific and not router-specific.

**Comment by DatanoiseTV** [comment]
I will look how we can get RSSI in a passive scan.

By the way: Are the "bluetooth" and "wifi" just keywords? Can any extra tag be used? Could we include other sources like LoRa here, as long as it uses a 6 octet MAC address?

**Comment by albinekb** [comment]
@datanoisetv do you have any rough numbers of what you could get in power usage/battery life?

**Comment by david81** [comment]
Was passive scanning ever added? I'd love to setup a few scanners around the house to use either phones or ble beacons for different purposes (perhaps a ble beacon in the car to detect when it's parked in the garage)
