### ISSUE TITLE
[Question] Boltdb vs Sqlite

### ISSUE THREAD

**Issue by thiamsantos** [schollz/find3#39]
What motivated you to change the database from Boltdb to Sqlite? I am considering to do the same in a project of mine and I would like to know what were your reasons to do it.

Thanks in advance.

**Comment by schollz** [comment]
I really wanted to have SQL to query things. I know that [Storm, the BoltDB toolkit](https://github.com/asdine/storm) can do this, but with SQLite I knew I wouldn't have to re-write a lot of things (database dumping/loading) and I knew I wouldn't face any problems in querying.

**Comment by 89z** [comment]
I found this issue from a web search, I just wanted to link my issue from another repo. I tried SQLite and Storm with the same project, and Storm seems to be 100 times slower even for basic queries.
