### ISSUE TITLE
Getting started tutorial or real world example?

### ISSUE THREAD

**Issue by LasaleFamine** [schollz/find3#43]
Hello and thank you so much for this awesome project! 💯 

I have been reading the Docs and I have just got some dubts about starting developing an app on top of find3.
Could be awesome to have some getting started tutorial or a real app as example to understand how to use find3 nicely and smoothly.

Do you have any of these types of resources? Do you think is something that should be added in the future?

Thank you again!

**Comment by schollz** [comment]
Hi @LasaleFamine have you this tutorial https://www.internalpositioning.com/doc/tracking_your_phone.md ?  I made it to help get started smoothly, but please let me know if you need other assistance or if the tutorial needs some more explanation.

**Comment by LasaleFamine** [comment]
Hey @schollz, actually I have checked the tutorial and I must admit that I read it superficially.
I'm more interested in passive tracking and I didn't realize that there is a specific page for that. My fault, sorry! 

Anyway, just not to waste the issue, I think can be useful to see some real use cases within the doc, you can show instantly the real potential of the library :+1:

We can close this one for me :)

**Comment by schollz** [comment]
Okay, please do let me now if you find something unclear in the passive tracking tutorial. I'm happy to make it more clear if I hear someone is struggling with some part of it.

Also feel free to [pose questions to the Slack channel](https://join.slack.com/t/find3/shared_invite/enQtMzI0MjkwMjc3MDYzLWJiZWEzZjU5NTljM2JlYmE1MDY0NThiYmY2NDYwNGYxNTNmNTJjZjFmNjMwNGMwY2UyNzczNzZhZTIxZWY3ODQ) too!
