### ISSUE TITLE
Learning flag

### ISSUE THREAD

**Issue by misisnik** [schollz/find3#49]
I have big data in another sqlite database (Find uncompatible) and it takes a while to put it into the Find database via request because its learning in each request 

I need only api.SaveSensorData(p) and i will learn the database after it will be complete..

So maybe put some flag for it ?
Thanks Mike

**Comment by schollz** [comment]
Added in https://github.com/schollz/find3/commit/b5408018156a21c86861decddbf52a976be4715d

Just use `/data?justsave=1` and nothing will be computed when inserting data.
