### ISSUE TITLE
[QUESTION] resolution with wifi mesh systems

### ISSUE THREAD

**Issue by yajrendrag** [schollz/find3#51]
wondering how the find3 algorithms work with wifi mesh systems such as orbi (not really true mesh), velop, etc.  does each node in the mesh constitute a separate physical wifi access point from a find3 perspective?  in other words are the wifi fingerprints a result of the distance & signal calculation to each individual wifi mesh node (as if they were independent wifi access points) or do the distance/signal calculations treat the entire mesh (group of wifi APs) as a single entity?

i'm curious because i am encountering some resolution issues that i don't seem to see with find version 2 and am wondering if this is related or not.  For example, overall it seems to take longer for find3 to converge on location changes - in particular, when i change locations between 2 rooms that each have a wifi mesh node, it's almost as if it doesn't detect the change until i make the find3 scanner on my android the front most app on the phone.  if i leave it in the background, it doesn't seem to detect the location change  - or it takes a really long time (minutes).  Find 2 in comparison, picked up changes almost immediately - but it also had erroneous changes.  once, find 3 has settled on what is the correct location, it doesn't seem to fluctuate.

I haven't tested this exhaustively, but the wifi mesh made me wonder.  Maybe it's just a learning issue still?  (although my accuracy overall is 98% and none individual locations are less than 92%)

thx, jay

**Comment by schollz** [comment]
@yajrendrag I think this is a learning issue. I don't think it has anything to do with WiFi mesh, although I've never played with them so I can't say for sure.

The location classification in FIND3 is very different than the previous version. It will be better in most cases, I suspect, but not in every case apparently. I would try to do more learning to see if it improves.

**Comment by yajrendrag** [comment]
thanks.  am thinking you're right.  i also switched over to passive scanning and have a series of questions - will make a new topic for them.
