### ISSUE TITLE
Deleted family re-appears

### ISSUE THREAD

**Issue by Thomas499** [schollz/find3#58]
One of my friends built the private server as instructed on the website. He noticed the delete family command deleted the data temporary, but then a few minutes later it was repopulated with the same data that was deleted. - Is the data stored somewhere in cache or is it possible the delete family command only deleted what the a.i. learned?

**Comment by schollz** [comment]
No, its not. What did your friend see that was repopulated? The dashboard? An API call? I cannot reproduce this when I try with `testdb`.

**Comment by Thomas499** [comment]
The Friend typed this - We first noticed that the app was making predictions with the same results as before the deletion with no new training data sent. Info seen in the database may have been what was sent for locating purposes, but the predictions occurring raised red flags.

**Comment by schollz** [comment]
What do you mean "making predictions"? Where did you see these predictions? On the dashboard? Or through an API call?

**Comment by schollz** [comment]
Can you post the commands, out the results of the two commands? The `DELETE` and then the API call that you make?

**Comment by schollz** [comment]
https://github.com/schollz/find3/issues/66#issuecomment-382998197
