### ISSUE TITLE
Add an iOS app with bluetooth support 

### ISSUE THREAD

**Issue by Thomas499** [schollz/find3#63]
I understand IOS will block any app that tries to use wifi rssi readings to determine location. Something about superior privacy policy. But is there anything in the IOS policy that will prevent an app from only only using BLE RSSI as long as no WiFi RSSI is used in the app?

**Comment by schollz** [comment]
@Thomas499 I don't know the answer to the question. But if it is possible to just use BLE RSSI, an app could be made for iOS (not by me since I have no Apple things).

Also it is possible to monitor iOS locations with Passive scanning (as long as they are tethered).

**Comment by Thomas499** [comment]
Do you have any documentation on how to tether an iOS phone to the system?

I will dig into seeing if iOS will allow BLE RSSI to be used. I will post what I find out. It might be a few days.

**Comment by Thomas499** [comment]
Update: I found your documentation regarding tethering here [https://github.com/schollz/find3/blob/master/doc/passive_tracking.md](url)

**Comment by schollz** [comment]
@makslevental Yes, it means connected to a wifi network.

**Comment by Thomas499** [comment]
@schollz  

1. Is there a way to do passive scanning using bluetooth? 

2. The device can only be tethered to one WiFi broadcasting device at a time correct? Doesn't the system require readings from multiple points to be accurate? How can this happen in passive scanning mode if the phone can only be tethered to one modem at a time?

**Comment by schollz** [comment]
1. Yes, the passive scanner tool already does passive scanning with bluetooth. Bluetooth is device-device so its a lot easier to implement. However, it only works when a device has bluetooth on and in "discoverable" mode. Android limits discoverable mode for 2 minutes, so its not much use for tracking phones.

2. Yes, a device can only be tethered to one router at a time. However, while it is tethered it will send out broadcasts looking for other (better) routers. This happens ~2 minutes when an Android phone is being used. FIND3 uses these broadcasts, which is how it works.

**Comment by schollz** [comment]
Closed due to https://github.com/schollz/find3/issues/66#issuecomment-382998197
