### ISSUE TITLE
Get Help link on Dashboard is bad link 

### ISSUE THREAD

**Issue by Thomas499** [schollz/find3#65]
![image](https://user-images.githubusercontent.com/38442058/38886266-71d297c8-4243-11e8-8037-03f1ac6f05ce.png)

![image](https://user-images.githubusercontent.com/38442058/38886194-3977e7de-4243-11e8-9b78-942150ca4eb2.png)

**Comment by 40345839668** [comment]
Sorun bağlantı değil yoğun iş temposu.

**Comment by Thomas499** [comment]
I think translated the first part means "problem no connection" my Turkish is a bit weak I didn't understand the second part.

**Comment by schollz** [comment]
Fixed: https://github.com/schollz/find3/commit/97a9ecbe684fabd98915e92eb94350dbd7468303
