### ISSUE TITLE
Allow user to select which machine learning to use

### ISSUE THREAD

**Issue by Thomas499** [schollz/find3#66]
Would it be possible to program into equation if a few modems disappear it doesn't effect the outcome too much. I noticed if I train with 12 WiFi signals detected, and then take away the 6 farthest modems, the code can't figure out the location. 

Realistically, over two years many of the BLE and WiFi signals will change. Neighbors get new WiFi modems or add extenders, BLE devices are replaced or eliminated. WiFi hotspots never stay in the same place for long. etc.

As long as 6 of 12 signals are detected with the same readings that they should have for that room, I don't see why it wouldn't be possible to code in some kind of solution that ensures this scenario doesn't result in unknown location.

**Comment by schollz** [comment]
Some algorithms are better at handling this at others. Since FIND3 uses many algorithms, some of them could be throwing off the tracking since it was not learned that way. In particular NB should totally prevent this problem. 

I guess the solution to this might be to allow the user to custom select their machine learning algorithms. Each has its own benefit, and in this case I would advise completely switching to NB (three versions of it).

**Comment by Thomas499** [comment]
I have another question as well. 

If you train with 12 wifi modems. Then you take 6 wifi modems away and notice the find accuracy is terrible. 

My question is: If you train with WiFi and BLE and when you do the find location, Bluetooth is turned off on the phone, will this effect the accuracy to the same degree as what happened when 6 WiFi modems were turned off?

**Comment by schollz** [comment]
> In that case, if you do decide to implement a way to allow user to select which machine learning to use, I would recommend a description of how each works or at the very least, the pro's and con's of each approach and how they would effect the outcome in different scenarios used in location identification.

Yes, that would be useful.

> If you train with 12 wifi modems. Then you take 6 wifi modems away and notice the find accuracy is terrible.

Again, this is not always the case. It depends which modems you take away. For example, I use passive scanning in my home and I only have three scanners. I can take one of them away and still get similar accuracy. In your case, I bet you take away the modems that are nearest to the locations, which would probably remove the strongest predictor of the locations.

> If you train with WiFi and BLE and when you do the find location, Bluetooth is turned off on the phone, will this effect the accuracy to the same degree as what happened when 6 WiFi modems were turned off?

No, as I said before, the system will work fine if access points "disappear". I've used this in airports and found that I could still positions myself despite being in the airport weeks later (airports have probably the greatest density of "mobile hotspots" as many people use them to use internet). As long as the most descriminating points don't disappear, the system should work fine. A discriminating point could probably be determined using PCA.

**Comment by schollz** [comment]
Yes, that would be useful

**Comment by Thomas499** [comment]
Can you make a recommendation on how to best collect the sample data for you? I can probably code it into the app to send the data to my email if needed but if you know of a quicker way to collect this sample data for you I'd appreciate it.

**Comment by schollz** [comment]
@Thomas499 See the testing framework I made: https://github.com/schollz/find3/issues/61#issuecomment-382992865. You can use that and filter out mac addresses and see how it affects the results.

**Comment by schollz** [comment]
Also @Thomas499, I've noticed that you joined Github [three days ago](https://github.com/Thomas499) and that your database name corresponds very closely to a LLC with an employee similar to your username. Thus, I think its reasonable to assume you are attempting to use FIND/FIND3 for business purposes. Depending on how you use it, it's totally within the license (though, note FIND is AGPL and FIND3 is MIT), however I don't offer free continual support for businesses. If you would like support for your business with FIND/FIND3, I do offer consulting. My email is hypercube.platforms@gmail.com if you'd like to discuss privately.

**Comment by 40345839668** [comment]
Yes, I did not add WiFi or cloud, but this does not mean I can not add my dear friends.

**Comment by 40345839668** [comment]
In addition, the reason for a 12-second delay is that the processor's Intel 2 Duo and graphics card only 2 gb. do you have a better idea?

**Comment by Thomas499** [comment]
Correct, I did start that business about 4 years ago. No website, do have a few college Interns working on a project. No investor funding. Intern will be receiving a final class grade based on use of working with API's soon. 

I will be happy to support your buy me a beer page. I planned on doing that anyway once we knew find3 was more accurate than original find. - If you are proposing contract programming work rather than just consulting I would be more interested. You seem to know what you are doing and pick up things quickly. Just realize, my access to funds is limited. - I'm just trying to get to the point where potential investors would be interested in helping out. 

We can continue this conversation by email if you would like. 

> In addition, the reason for a 12-second delay is that the processor's Intel 2 Duo and graphics card only 2 gb. do you have a better idea?

My upload speed is only 6 mb/s (max) and the two room mates already complain about lag on the upload speed when they are playing their ps4's from time to time. A new internet company is in town installing fiber which would allow equal upload and download speed but they aren't installing on this street for at least another 6 months. Once they do, if it is possible to share the server load i'd be willing to have that conversation with you. The intern does have his own server set up but I have no idea what hardware he is using or its capabilities. - I will ask the intern if he has any ideas when I see him this weekend. 

> FIND3 is MIT

Why is this running only on an Intel 2 Duo and graphics card then?
