### ISSUE TITLE
Find3 server is down

### ISSUE THREAD

**Issue by Thomas499** [schollz/find3#68]
![image](https://user-images.githubusercontent.com/38442058/39029784-a617b33a-442b-11e8-88da-a57bcef2679c.png)

**Comment by schollz** [comment]
was a caddy issue, now its up

**Comment by Thomas499** [comment]
Still seems to be an issue

![image](https://user-images.githubusercontent.com/38442058/39065521-0dd444d8-44a0-11e8-8dc3-39f83c561ca8.png)

**Comment by WagnoLeaoSergio** [comment]
The Find3 server is down again

**Comment by WagnoLeaoSergio** [comment]
![image](https://user-images.githubusercontent.com/36570614/61736888-72237180-ad5d-11e9-8b66-b1cc74c8d0f5.png)
