### ISSUE TITLE
MQTT server authentication even with invalid credentials

### ISSUE THREAD

**Issue by abhilash1in** [schollz/find3#70]
I passed `MQTT_ADMIN`, `MQTT_PASS` and `MQTT_SERVER` env variables to my docker container. Yet, I AM ABLE TO connect to the MQTT server, publish and subscribe using any arbitrary credentials. 

- Should I add quotes in the values for my env variables `MQTT_ADMIN` and `MQTT_PASS`? The example `MQTT_SERVER='localhost:1883'` has quotes around the value. Basically, should it be `MQTT_ADMIN='test'` or `MQTT_ADMIN=test`? I tried both and in both cases, I was able to authenticate with the MQTT server even with wrong credentials. 

- Is this intended behavior? Is it possible to restrict only the admin to connect, publish and subscribe?

- Which credentials does find3 use for its MQTT client? The one provided via env variables?

- `mosquitto_config/passwd` and `mosquitto_config/acl` are empty. Is this intended behavior?

**Comment by schollz** [comment]
Sounds like somethings wrong. Did you find anything else?

**Comment by schollz** [comment]
@abhilash1in @fermuch this should be fixed now

**Comment by fermuch** [comment]
I'll try again some day this week and report back.
