### ISSUE TITLE
[question] Why find3 is storing randomized MACs?

### ISSUE THREAD

**Issue by hit0ri** [schollz/find3#73]
Currently my database has ~14k (~19k total) devices with randomized android MACs (`da:a1:19:*`) and I'm curious if they are being used or they just causing constant database growth?

**Comment by schollz** [comment]
You are using passive scanning, correct? In that case, yes, random mac addresses are discovered and saved. I don't want to assume that they are not useful (in fact, if you are interested in using FIND to measure how many people are in a certain area, it is quite useful) so I do not delete them. 

Right now there is now API to delete them, but maybe their could be? The space is not such an issue, but it would make the database queries faster.

**Comment by hit0ri** [comment]
I think having an option for find3-cli-scanner to ignore random MAC addresses and an API to delete them would be useful.

 Should I open feature requests?

**Comment by schollz** [comment]
Sure, or better, submit a PR! It's very easy to do - the code for finding random mac addresses [is already written](https://github.com/schollz/find3/blob/4e15ed0f2ee91657e5c4e8c2e73b1d09c20095c2/server/main/src/utils/utils.go#L61-L77). It's just a matter of copy and pasting it into the scanner, adding a flag, and then checking whether to skip the address when adding them from the for loop.

**Comment by schollz** [comment]
This is now an option in the CLI scanner: https://github.com/schollz/find3-cli-scanner/commit/98768f9c85ef4949236b5cd16bf2c9751a64bfa1
