### ISSUE TITLE
Using passive scanning to detect a bluetooth beacon 

### ISSUE THREAD

**Issue by albertreed** [schollz/find3#76]
I'm researching tools and technologies for a little home-automation project I'm working on. I have a bunch of [Eddystone beacons](https://developers.google.com/beacons/eddystone) that I'm looking to track around my site. The documentation talks mostly about passive scanning for wifi. Will find3-cli-scanner running on Rasberry Pi with the -passive flag also pick up bluetooth or is it wifi-only?

Thanks much! Looking forward to working with and contributing to the project.

**Comment by albertreed** [comment]
Nevermind - this was super easy to rig up on my own so I just did that. Sorry for the noise!

**Comment by ifnull** [comment]
@albertreed was this out of box functionality or something you customized? I'm looking to do the same.

**Comment by albertreed** [comment]
Something I rigged up. It was quite straightforward though - just gathered the bluetooth signal strengths from the beacon detectors reversed them and sent them to the active (not passive) API.

**Comment by ifnull** [comment]
@albertreed are you using the CLI scanner at all? I was thinking of using the beacontools package for python to collect the addr and rssi and send to API. Maybe I'm overthinking this, but what would be the inverse of the beacon rssi?

**Comment by albertreed** [comment]
I am not using the CLI scanner. The reversing that needs to happen isn't with RSSI, it's with the transmitter and receiver. I've got BLE beacons and a bunch of BLE sensors scattered about. To the find3 server's /data endpoint I send:
d: an ID for the _beacon_
f: usual
t: the current time
l: if I'm training, the location of the beacons
s: { bluetooth: {
   Map of sensor IDs that have detected the beacon -> RSSI
}}

There is some complexity that I forgot about: each sensor needs to send it's data off to something that can aggregate the information. Since that data comes in at different times, I aggregate the readings from the sensors over a short window and then send it off to Find3.

It's totally possible this duplicates the existing Find3's Passive functionality. I never checked.

Hope this helps!

Cheers,
Al

**Comment by suiluj** [comment]
@albertreed hi i am planning to to something similar (passive phone tracking via bluetooth)
may i ask which devices you use as bluetooth sensor? and did you publish your aggregate script somewhere? (perhaps we are lucky ;) )

Regards,
Julius

**Comment by albertreed** [comment]
I'm using Raspberry Pi Zeros. Sadly, I don't have anything reusable to share.

**Comment by tlrobinson** [comment]
Does anyone have more details about how to do this? It would be great if it were built into find3.

**Comment by nash-stokes** [comment]
Struggling with this as well. Any help would be appreciated. I feel like this is now possible with passive scanning, but I don't think I'm implementing it correctly.

**Comment by tlrobinson** [comment]
@nash-stokes I used ESP32s with ESPHome to create sensors in Home Assistant, and Node-RED to send data in the right format to find3. It’s definitely more complicated than it needs to be.

Two relevant issues here:

* https://github.com/esphome/feature-requests/issues/288
* https://github.com/schollz/find3/issues/135
