### ISSUE TITLE
How to connect to mqtt server

### ISSUE THREAD

**Issue by fermuch** [schollz/find3#77]
According to #25 the docker admin and pass should be set by env vars (`MQTT_ADMIN` and `MQTT_PASS`). I've setted these two, and then subscribed to the server with `#` to get all messages.

By subscribing to `$SYS` I can see there are 32 subscriptions active, but I can not see anything except for data I publish. Sensor data is being upated on the site, which makes me believe there should be traffic on the mqtt server.

**Expected:**

- Subscribe to '#' with admin user
- See all data from find3

**Actually happening:**

- Subscribe to '#' with admin user
- Nothing is published, ever.

-------

I've also noticed *any* user can connect to the server, as said in #70

**NOTE:** I'm using the docker image.

**Comment by schollz** [comment]
Yeah something is wrong with MQTT on Docker it seems. I will give it a look in a week or so. Let's merge this discussion with #70
