### ISSUE TITLE
Slack Invite Link is Dead

### ISSUE THREAD

**Issue by meyerscr** [schollz/find3#78]
I wanted to join your slack channel because I'm a Data Science student who would love to contribute. However, the slack link on your readme is dead.

**Comment by schollz** [comment]
https://join.slack.com/t/find3/shared_invite/enQtMzU4MjY0NjE1NjU0LWRkY2JhNWFkM2U3Y2JhY2RlZTQ5ZTdmZTQ2M2UzMjI2MGVmMjZlOWQyZmU3MzM5YzIzOTM0YmYzYmQ3NTQzNjQ
