### ISSUE TITLE
Memory leak in server? Also - api/v1/by_location is very slow and CPU/memory intensive?

### ISSUE THREAD

**Issue by victorhooi** [schollz/find3#8]
I have a find3 server running on a Google Compute Engine instance - `n1-standard-1 (1 vCPU, 3.75 GB memory)`.

I have five Raspberry PIs that are scanning, and sending fingerprints to this server. I have done training, and added around 8 locations.

I'm using `docker stats find3server` to track memory usage of `find3server`.

The memory usage starts out at around 193 MB. However, there seem to be two issues.

Firstly, over time the Docker instance appears to consume memory (and not release it), and eventually consumes all machine and crashes the host machine.

Secondly, if you call the http://server:8003/api/v1/by_location/family_name endpoint, this seems to accelerate the process - it seems to add a few hundred MB each time.

For example - initial memory:

<img width="904" alt="screen shot 2018-03-04 at 10 39 31" src="https://user-images.githubusercontent.com/243499/36943083-c3dd25c2-1fd6-11e8-952c-1aa4d024c8fa.png">

Then, calling `http GET SERVER_IP_ADDRESS:8003/api/v1/by_location/gcc` - new screenshot of `docker stats find3server` after each call:

<img width="919" alt="screen shot 2018-03-04 at 10 42 35" src="https://user-images.githubusercontent.com/243499/36943093-ddb2b1b0-1fd6-11e8-8b41-658dea5a4c87.png">
<img width="890" alt="screen shot 2018-03-04 at 10 45 05" src="https://user-images.githubusercontent.com/243499/36943094-e14b4d46-1fd6-11e8-8d39-427cbd90c10c.png">
<img width="895" alt="screen shot 2018-03-04 at 11 04 57" src="https://user-images.githubusercontent.com/243499/36943095-e4694b5e-1fd6-11e8-956b-14222233835c.png">
<img width="915" alt="screen shot 2018-03-04 at 11 30 11" src="https://user-images.githubusercontent.com/243499/36943097-e6e27afe-1fd6-11e8-874e-a8da50dc4c0e.png">
<img width="914" alt="screen shot 2018-03-04 at 11 46 26" src="https://user-images.githubusercontent.com/243499/36943098-e908df76-1fd6-11e8-9d30-97c383a4e2e2.png">
<img width="939" alt="screen shot 2018-03-04 at 12 02 22" src="https://user-images.githubusercontent.com/243499/36943099-ec040bc4-1fd6-11e8-8dba-2036179850b2.png">

However, even just leaving the machine alone, the memory usage climbs on its own.

Also, each request against `api/v1/by_location/<family>` takes longer and longer.

I had to change the httpie timeout from the default of 30 seconds, to 5 minutes, then 10 minutes, to let it complete. After around 5 calls, it would no longer complete even after 10 minutes.

Also - even after restarting the entire machine, and starting `find3server` up again - api/v1/by_location still won't complete within 10 minutes =(.

**Comment by schollz** [comment]
I'm almost certain this has to do with my Naive bayes implementation. Can you send me your database file to checkout ? You can put in the slack channel. (Its in the /data directory with some name like *.sqlite3.db)

**Comment by victorhooi** [comment]
Data file is attached;

[bjAa.sqlite3.db.zip](https://github.com/schollz/find3/files/1786497/bjAa.sqlite3.db.zip)

**Comment by victorhooi** [comment]
I tried with the latest git pull, after some of the recent Naive Bayes changes:

https://github.com/schollz/find3/commit/7d00ee4568ac7ff5ea43a89058a409ecf8224f89
https://github.com/schollz/find3/commit/591c2dc903a6fb9e793f85a883e069d211d108a6

Memory usage seems slightly better - but still very high, and doesn't release:

```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
find3server_newml   1.56%               1015MiB / 3.607GiB   27.49%              1.1MB / 448kB       63.1MB / 771MB      28
```

Also - the command still times out after 10 minutes:

```
victorhooi@victorhooi-wiki:~$ http --timeout=600 GET localhost:8003/api/v1/by_location/gcc >> ~/gcc_results

http: error: Request timed out (600.0s).
```

Anything else I should try?

**Comment by schollz** [comment]
This should be fixed now, as I found the error was from not closing loggers when generating them.

**Comment by cpressman** [comment]
I notice this was closed 2 years ago but I have been experiencing something very similar. When I go into the docker container using docker exec -ti find3server /bin/bash and then running top I can see that flask memory is growing substantially (30% ) and main as well (10%). This continues to happen until restarting the container frees the memory.
