### ISSUE TITLE
Importing RandomForestClassifier twice

### ISSUE THREAD

**Issue by aaasp18** [schollz/find3#82]
https://github.com/schollz/find3/blob/1900fd0bb78f57ae353baa6af509716bdd37ab87/server/ai/src/learn.py#L32
https://github.com/schollz/find3/blob/1900fd0bb78f57ae353baa6af509716bdd37ab87/server/ai/src/learn.py#L41

**Comment by schollz** [comment]
Thanks https://github.com/schollz/find3/commit/4f420bc35a380c6c2850c2592202f4e7acdbaabb
