### ISSUE TITLE
Slack link no longer active

### ISSUE THREAD

**Issue by tmladek** [schollz/find3#84]
I tried to join the slack development channel and got only a page that says:

> 
> This invite link is no longer active.
> 
> Please check with the person who shared it with you to see if there's a new link available.

**Comment by schollz** [comment]
Where did you find this link?

[All links are the same](https://github.com/schollz/find3/search?utf8=%E2%9C%93&q=shared_invite&type=), and I just tested them on a new account and it worked fine.

**Comment by tmladek** [comment]
Hi, I see they are the same, but upon opening, I simply get the message described above. Attached you'll find a screenshot in a private session (thus eliminating any Slack state that might be specific to me).

![2018-05-07 15_28_58-create account _ slack](https://user-images.githubusercontent.com/5217341/39704430-8fc0950a-520b-11e8-9700-14f6f7aa579b.png)

**Comment by schollz** [comment]
@tmladek Where did you find this link?

**Comment by tmladek** [comment]
In the README of this repository, as I stated above; it is indeed the same as in the search you linked me to, as you can see in the address bar in the screenshot that I posted.

**Comment by tmladek** [comment]
In the README of this repository.

https://raw.githubusercontent.com/schollz/find3/master/README.md

**Comment by schollz** [comment]
The URL in the Readme isn't the same as the URL in your screenshot @tmladek

**Comment by tmladek** [comment]
It absolutely is for me, and I feel like I just entered a Twilight Zone of URLs:

![2018-05-10 11_51_30-https___raw githubusercontent com_schollz_find3_master_readme md](https://user-images.githubusercontent.com/5217341/39863978-8d023582-5448-11e8-8a20-53e2475d47c7.png)
