### ISSUE TITLE
Improving Accuracy

### ISSUE THREAD

**Issue by yajrendrag** [schollz/find3#85]
Using find3 with passive scanning of bluetooth.   I moved from scanning of android wifi because it seems i have to force the phone's screen to stay on (i have a samsung Galaxy S8) in order for the tracking to register.  so if the phone goes to sleep or whatever it does for long periods of inactivity, then scanning doesn't seem to register.

Instead i had some BLE beacons - and they seem to work pretty well - they update about every minute.

But, i'm finding some large swings in reported location probability and wondering if that is just learning or if there is something else i can do.  I have 60-80 data points for each location.  And with the beacon not moving (all day in some cases), the reported location is constantly changing.  And the probability swings are huge - for example:

```
{"location":"den","probability":0.74},{"location":"master bedroom","probability":0.12}
{"location":"master bedroom","probability":0.5},{"location":"den","probability":0.45}
```

& this goes on all day...

these readings are a minute apart.. and the beacon hasn't moved.  so 1 minute it reports in the den, the next it's in the master bedroom.  These 2 physical locations are (using an x-y plane to explain the distance separation) about 30 feet apart on the y axis and 3 feet apart on the x axis.

Does this simply point to more learning?  if so, any suggestion on how much more?  the 60-80 data points were done about 20-30 minute in length on 2 different occasions.  Or would more passive scanners help?  other thoughts - is this amount of fluctuation normal?

thx, Jay

**Comment by schollz** [comment]
Can you send me the database or your group name if using the public server?

**Comment by yajrendrag** [comment]
using my own server.    should i copy it and put it somewhere you can get to it?

**Comment by schollz** [comment]
You can attach it in the slack channel
