### ISSUE TITLE
Add front-end page to list locations, devices seen there, and total

### ISSUE THREAD

**Issue by victorhooi** [schollz/find3#9]
It would be awesome if there was a front-end page that was the equivalent of the API call:

http://server:8003/api/v1/by_location/FAMILY_NAME

This could list:
- Name of each location
- List of devices who have their last-seen location as there (or within last 15 minutes)
- Total number of devices for that location

**Comment by schollz** [comment]
Sure, that's a good idea. I can look at making another react page for that.

**Comment by schollz** [comment]
Forgot, this was done awhile ago.
